Fix compile errors:
F:\Projects\ServUOPub57-Rebirth\ServUO\Scripts\Custom\Items\OneTimeRewardStone\OneTimeRewardStone.cs(26,24):
- error CS1061: 'PlayerMobile' does not contain a definition for 'HasTag' and no accessible extension method
- 'HasTag' accepting a first argument of type 'PlayerMobile' could be found (are you missing a using directive or an assembly reference?)